version: '3'
services:
  api:
    build: .
    ports:
      - 80:8000
    volumes:
      - ./:/user/src/app
    env_file:
      - ./.env/.local
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    env_file:
      - ./.env/.local
    ports:
      - 5432:5432
volumes:
  postgres-db: